@startuml
annotation java.lang.Override
class Jama.Matrix
class ij.IJ
class ij.ImagePlus
class ij.ImageStack
class ij.gui.Roi
class ij.io.FileSaver
class ij.plugin.RoiScaler
class ij.plugin.filter.GaussianBlur
class ij.process.FloatProcessor
class ij.process.FloatStatistics
class ij.process.ImageProcessor
class java.awt.Frame
class java.awt.Rectangle
class java.awt.event.ActionListener
class java.awt.event.KeyEvent
class java.awt.event.MouseEvent
class java.io.File
class java.io.FileNotFoundException
class java.io.FileReader
class java.io.IOException
class java.lang.Math
class java.lang.Object
class java.lang.Thread
class java.util.ArrayList
class java.util.Arrays
class java.util.Comparator
class java.util.List
class java.util.logging.Level
class java.util.logging.Logger
class javax.swing.DefaultListModel
class javax.swing.JDialog
class javax.swing.JFileChooser
class javax.swing.JFrame
class javax.swing.JList
class javax.swing.UIManager
class ndl.ndllib.ArrayList
class ndl.ndllib.DataTrace_ver1
class ndl.ndllib.DataTrace_ver_3
class ndl.ndllib.DataTrace_ver_inwrks
class ndl.ndllib.ImageDifferentials
class ndl.ndllib.J2DVectorPolar
class ndl.ndllib.JHeatMapArray
class ndl.ndllib.JVector
class ndl.ndllib.JVectorCmpImg
class ndl.ndllib.JVectorSpace
class ndl.ndllib.MultiFileDialog
class ndl.ndllib.MultiSelectFrame
class ndl.ndllib.NDLlib
class ndl.ndllib.OrdXYData
class ndl.ndllib.OrdXYData_1
class ndl.ndllib.OrdXYErrData
class ndl.ndllib.OrdXYErrData_inVer2
class ndl.ndllib.Scoring_Assistant
class ndl.ndllib.SurfaceFit
class ndl.ndllib.TraceData
class ndl.ndllib.Tracker
class ndl.ndllib.TrackerImplement
class org.opencv.core.Mat
class org.opencv.imgproc.Imgproc
class org.opencv.imgproc.Moments
class org.opencv.videoio.VideoCapture
interface java.awt.event.KeyListener
interface java.awt.event.MouseListener
ndl.ndllib.DataTrace_ver1 ..> java.lang.Override
ndl.ndllib.DataTrace_ver1 --|> ndl.ndllib.ArrayList
ndl.ndllib.DataTrace_ver_3 ..> java.lang.Override
ndl.ndllib.DataTrace_ver_3 ..> java.io.File
ndl.ndllib.DataTrace_ver_3 ..> java.io.FileNotFoundException
ndl.ndllib.DataTrace_ver_3 ..> java.io.FileReader
ndl.ndllib.DataTrace_ver_3 ..> java.io.IOException
ndl.ndllib.DataTrace_ver_3 ..> java.lang.Math
ndl.ndllib.DataTrace_ver_3 --|> ndl.ndllib.ArrayList
ndl.ndllib.DataTrace_ver_inwrks ..> java.lang.Override
ndl.ndllib.DataTrace_ver_inwrks ..> java.io.File
ndl.ndllib.DataTrace_ver_inwrks ..> java.io.FileNotFoundException
ndl.ndllib.DataTrace_ver_inwrks ..> java.io.FileReader
ndl.ndllib.DataTrace_ver_inwrks ..> java.io.IOException
ndl.ndllib.DataTrace_ver_inwrks ..> java.lang.Math
ndl.ndllib.DataTrace_ver_inwrks ..> java.util.logging.Level
ndl.ndllib.DataTrace_ver_inwrks ..> java.util.logging.Logger
ndl.ndllib.DataTrace_ver_inwrks --|> ndl.ndllib.ArrayList
ndl.ndllib.ImageDifferentials ..> ij.process.ImageProcessor
ndl.ndllib.J2DVectorPolar ..> java.util.ArrayList
ndl.ndllib.J2DVectorPolar --|> ndl.ndllib.JVector
ndl.ndllib.JHeatMapArray --|> java.lang.Object
ndl.ndllib.JHeatMapArray ..> java.util.ArrayList
ndl.ndllib.JVector ..> java.util.ArrayList
ndl.ndllib.JVector ..> java.util.Arrays
ndl.ndllib.JVectorCmpImg ..> ij.IJ
ndl.ndllib.JVectorCmpImg ..> ij.ImagePlus
ndl.ndllib.JVectorCmpImg ..> ij.ImageStack
ndl.ndllib.JVectorCmpImg ..> ij.io.FileSaver
ndl.ndllib.JVectorCmpImg ..> java.io.File
ndl.ndllib.JVectorSpace ..> java.util.ArrayList
ndl.ndllib.MultiFileDialog ..> java.awt.event.ActionListener
ndl.ndllib.MultiFileDialog ..> java.io.File
ndl.ndllib.MultiFileDialog --|> javax.swing.JDialog
ndl.ndllib.MultiSelectFrame ..> java.awt.event.ActionListener
ndl.ndllib.MultiSelectFrame ..> java.io.File
ndl.ndllib.MultiSelectFrame ..> javax.swing.DefaultListModel
ndl.ndllib.MultiSelectFrame --|> javax.swing.JFrame
ndl.ndllib.MultiSelectFrame ..> javax.swing.JList
ndl.ndllib.MultiSelectFrame ..> javax.swing.UIManager
ndl.ndllib.OrdXYData --|> java.lang.Object
ndl.ndllib.OrdXYData ..> java.util.ArrayList
ndl.ndllib.OrdXYData_1 ..> java.lang.Override
ndl.ndllib.OrdXYData_1 --|> java.lang.Object
ndl.ndllib.OrdXYErrData ..> java.lang.Override
ndl.ndllib.OrdXYErrData ..> java.util.ArrayList
ndl.ndllib.OrdXYErrData --|> ndl.ndllib.OrdXYData
ndl.ndllib.OrdXYErrData_inVer2 ..> java.lang.Override
ndl.ndllib.OrdXYErrData_inVer2 ..> java.lang.Math
ndl.ndllib.OrdXYErrData_inVer2 --|> ndl.ndllib.OrdXYData
ndl.ndllib.Scoring_Assistant ..> ij.ImagePlus
ndl.ndllib.Scoring_Assistant ..> ij.ImageStack
ndl.ndllib.Scoring_Assistant --|> java.awt.Frame
ndl.ndllib.Scoring_Assistant ..> java.awt.event.KeyEvent
ndl.ndllib.Scoring_Assistant ..> java.awt.event.MouseEvent
ndl.ndllib.Scoring_Assistant ..> java.io.File
ndl.ndllib.Scoring_Assistant ..> javax.swing.JFileChooser
ndl.ndllib.Scoring_Assistant --|> java.awt.event.KeyListener
ndl.ndllib.Scoring_Assistant --|> java.awt.event.MouseListener
ndl.ndllib.SurfaceFit ..> Jama.Matrix
ndl.ndllib.SurfaceFit ..> ij.ImagePlus
ndl.ndllib.SurfaceFit ..> ij.gui.Roi
ndl.ndllib.SurfaceFit ..> ij.plugin.RoiScaler
ndl.ndllib.SurfaceFit ..> ij.plugin.filter.GaussianBlur
ndl.ndllib.SurfaceFit ..> ij.process.FloatProcessor
ndl.ndllib.SurfaceFit ..> ij.process.FloatStatistics
ndl.ndllib.SurfaceFit ..> ij.process.ImageProcessor
ndl.ndllib.SurfaceFit ..> java.awt.Rectangle
ndl.ndllib.TraceData ..> java.lang.Override
ndl.ndllib.TraceData --|> java.lang.Object
ndl.ndllib.Tracker --|> java.lang.Thread
ndl.ndllib.Tracker ..> java.util.ArrayList
ndl.ndllib.Tracker ..> java.util.Arrays
ndl.ndllib.Tracker ..> java.util.Comparator
ndl.ndllib.Tracker ..> java.util.List
ndl.ndllib.Tracker ..> org.opencv.imgproc.Imgproc
ndl.ndllib.Tracker ..> org.opencv.imgproc.Moments
ndl.ndllib.Tracker ..> org.opencv.videoio.VideoCapture
ndl.ndllib.TrackerImplement ..> java.lang.Override
ndl.ndllib.TrackerImplement ..> org.opencv.core.Mat
@enduml